stages:
  - build
  - test
  - deploy

.docker:build:
  stage: build
  image: jdrouet/docker-with-buildx:stable
  services:
    - docker:dind
  before_script:
    - docker info
    - cd images/${VERSION}/php${PHP_VERSION}-${VARIANT}-${ARCHI}
  script:
    - ls -al
    # - docker buildx build --platform linux/amd64,linux/arm64 -t jdrouet/docker-with-buildx:stable .

docker:build:
  extends: .docker:build
  parallel:
    matrix:
      - VERSION: ['11.0', '12.0', '13.0', '14.0', '15.0']
        PHP_VERSION: ['7.4']
        VARIANT: ['fpm-alpine', 'fpm', 'apache']
        ARCHI: ['i386', 'amd64']
      - VERSION: ['16.0']
        PHP_VERSION: ['8.1']
        VARIANT: ['fpm-alpine', 'fpm', 'apache']
        ARCHI: ['i386', 'amd64']

  