---
version: '3.8'

services:
  docker-dolibarr:
    build: 
      context: ./images/16.0/php8.1-apache
      args:
        ARCHI: arm64
    healthcheck:
      test: curl --silent http://localhost:80|| exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockerdolibarr.rule=Host(`dolibarr.traefik.me`)
      - traefik.http.services.dockerdolibarr.loadbalancer.server.port=80
    volumes:
      - documents:/var/www/documents
      - scripts:/var/www/scripts
      - custom:/var/www/custom
    environment:
      DOLI_AUTO_CONFIGURE: 1
      DOLI_DB_TYPE: mysqli
      DOLI_DB_HOST: dolibarr_db
      DOLI_DB_PORT: 3306
      DOLI_DB_NAME: dolibarr_db
      DOLI_DB_USER: dolibarr_usr
      DOLI_DB_PASSWORD: mpsAL@3^a/3`v&Za
      DOLI_URL_ROOT: https://dolibarr.traefik.me
    networks:
      - dolibarr_network
      - dolibarr_db_network
      - traefik_router

  dolibarr_db:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MdPToRootU3rF0rD0li8aR
      MYSQL_DATABASE: dolibarr_db
      MYSQL_USER: dolibarr_usr
      MYSQL_PASSWORD: mpsAL@3^a/3`v&Za
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 600s
    volumes:
      - data:/var/lib/mysql
    networks:
      - dolibarr_db_network

# Docker Networks
networks:
  dolibarr_db_network:
  traefik_router:
    external: true
  dolibarr_network:

volumes:
  data:
  documents:
  scripts:
  custom:
